stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build --target builder -t electron:0.1-beta .
    - docker build --target proxy -t electron_proxy:0.1 .

test-job:
  stage: test
  script:
    - docker compose -f compose-test-run.yml up -d
    - docker exec test_backend pytest -s -v
    - docker compose down

deploy-job:
  stage: deploy
  script:
    - docker compose up -d