# Generated by Django 4.2.1 on 2025-01-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
