# Generated by Django 4.2.1 on 2025-01-31 14:53

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[validators.validate_image_type, validators.validate_image_size, validators.validate_image_integrity]),
        ),
    ]
